//! The ordinary Ethos-zero wire contract: the vocabulary of the Ethos Nexus
//! that follows ethos-zero, and the Library of names it shares with the meta
//! contract.
//!
//! `ethos/library.ethos` and `ethos/signal.ethos` are the authored sources
//! and the only interface; `src/generated/` holds their projection,
//! regenerated by ethos-zero and held byte-identical by `build.rs`. The
//! Signal imports the Library as `signal_ethos_zero:[ … ]`, the path every
//! importer names, this crate included.
//!
//! The contract rides signal's exchange layer. Its identity on the wire is
//! the digest of its authored sources, settled once per connection by the
//! greeting; two peers built from different sources refuse each other rather
//! than negotiate. The framing, the greeting and the exchange envelope are
//! signal's; this crate holds vocabulary only.

extern crate self as signal_ethos_zero;

pub mod generated;
pub use generated::library::*;
pub use generated::signal::*;

/// The authored Library: the names the ordinary and meta contracts share.
pub const LIBRARY: &str = include_str!("../ethos/library.ethos");

/// The authored Ethos sources this contract is generated from, the Library
/// then the Signal, and the one artefact its wire identity is computed over.
pub const ETHOS: &str = concat!(
    include_str!("../ethos/library.ethos"),
    include_str!("../ethos/signal.ethos")
);

/// The querying side is the side that greets, so the identity is borne by
/// the query root.
impl signal::Contracted for Query {
    const CONTRACT_SOURCE: &'static str = ETHOS;
}
