//! The ordinary Ethos-zero wire contract: the vocabulary of the Ethos Nexus
//! that follows ethos-zero.
//!
//! `ethos/signal.ethos` is the authored source and the only interface;
//! `src/generated/signal.rs` is its projection, regenerated by ethos-zero and
//! held byte-identical by `build.rs`.
//!
//! The contract rides signal's exchange layer. Its identity on the wire is
//! the digest of its authored source, settled once per connection by the
//! greeting; two peers built from different sources refuse each other rather
//! than negotiate. The framing, the greeting and the exchange envelope are
//! signal's; this crate holds vocabulary only.

pub mod generated;
pub use generated::signal::*;

/// The authored Ethos source this contract is generated from, and the one
/// artefact its wire identity is computed over.
pub const ETHOS: &str = include_str!("../ethos/signal.ethos");

/// The querying side is the side that greets, so the identity is borne by
/// the query root.
impl signal::Contracted for Query {
    const CONTRACT_SOURCE: &'static str = ETHOS;
}
